export const MUTATIONS = {
  CREATE_CART_ITEM: 'createCartItem',
  UPDATE_CART_FOOD_QUANTITY: 'updateCartFoodQuantity',
  DELETE_CART_ITEM: 'deleteCartItem',
  CREATE_FOOD: 'createFood',
  UPDATE_FOOD_BY_ID: 'updateFoodById',
  DELETE_FOOD_BY_ID: 'deleteFoodById',
  CREATE_CATEGORY: 'createCategory',
  UPDATE_CATEGORY_BY_ID: 'updateCategoryById',
  DELETE_CATEGORY_BY_ID: 'deleteCategoryById',
  CLEAR_USER_CART: 'clearUserCart',
  CREATE_COURIER: 'createCourier',
  DELETE_COURIER_BY_ID: 'deleteCourierById',
  UPDATE_ORDER_STATUS_BY_ID: 'updateOrderStatusById',
  DELIVER_ORDER_BY_ID: 'deliverOrderById',
  RECEIVE_ORDER_BY_ID: 'receiveOrderById',
  START_COOKING_FOOD: 'startCookingFood',
  CREATE_ORDER: 'createOrder',
  ATTACH_ORDER: 'attachOrder',
  ADD_FOOD_TO_FAVORITES: 'addFoodToFavorites',
  REMOVE_FOOD_FROM_FAVORITES: 'removeFoodFromFavorites',
  UPDATE_USER_BY_ID: 'updateUserById',
  SIGN_UP: 'signUp',
  CONFIRM_SIGN_UP: 'confirmSignUp',
  UPDATE_USER_PASSWORD_BY_ID: 'changeUserPasswordById',
};
