import { resolvers } from 'src/common';
import { Permissions } from 'src/types/permissions';

export const PERMISSIONS: Permissions = {
  user: resolvers(
    'CREATE_CART_ITEM',
    'CREATE_ORDER',
    'GET_FOOD_BY_ID',
    'UPDATE_CART_FOOD_QUANTITY',
    'GET_USER_BY_ID',
    'GET_ALL_FOODS',
    'GET_CART_ITEMS_BY_USER_ID',
  ),
  admin: resolvers(
    'CREATE_ORDER',
    'ATTACH_ORDER',
    'GET_COURIERS',
    'GET_FOOD_BY_ID',
    'CREATE_ORDER',
    'CREATE_CART_ITEM',
    'CREATE_FOOD',
    'GET_DASHBOARD',
    'GET_ALL_USERS',
    'GET_ALL_FOODS',
    'CREATE_COURIER',
    'GET_USER_BY_ID',
    'GET_ORDER_BY_ID',
    'UPDATE_FOOD_BY_ID',
    'GET_USERS_BY_PHONE',
    'CREATE_CATEGORY',
    'DELETE_COURIER_BY_ID',
    'GET_ALL_CATEGORIES',
    'GET_CATEGORY_BY_ID',
    'GET_ORDERS_BY_STATUS',
    'DELIVER_ORDER_BY_ID',
    'RECEIVE_ORDER_BY_ID',
    'START_COOKING_FOOD',
    'UPDATE_CATEGORY_BY_ID',
    'DELETE_CATEGORY_BY_ID',
    'UPDATE_ORDER_STATUS_BY_ID',
    'GET_CART_ITEMS_BY_USER_ID',
  ),
  courier: resolvers('DELIVER_ORDER_BY_ID'),
};
