export const QUERIES = {
  TELEGRAM_USER_LOGIN: 'telegramUserLogin',
  GET_ALL_USERS: 'getAllUsers',
  GET_DASHBOARD: 'getDashboard',
  GET_CART_ITEMS_BY_USER_ID: 'getCartItemsByUserId',
  GET_USER_BY_ID: 'getUserById',
  GET_FOOD_BY_ID: 'getFoodById',
  GET_ORDER_BY_ID: 'getOrderById',
  GET_USERS_BY_PHONE: 'getUsersByPhone',
  GET_ALL_FOODS: 'getAllFoods',
  GET_ALL_CATEGORIES: 'getAllCategories',
  GET_CATEGORY_BY_ID: 'getCategoryById',
  GET_FOODS_BY_CATEGORY: 'getFoodsByCategory',
  GET_ALL_COURIERS: 'getAllCouriers',
};
