import { resolvers } from 'src/common';
import { ResolversPermissions } from 'src/types/resolversPermissions';

export const RESOLVERS_PERMISSIONS: ResolversPermissions = {
  user: resolvers(
    'CREATE_CART_ITEM',
    'CREATE_ORDER',
    'GET_FOOD_BY_ID',
    'UPDATE_CART_FOOD_QUANTITY',
    'GET_USER_BY_ID',
    'GET_ALL_FOODS',
    'GET_CART_ITEMS_BY_USER_ID',
    'ADD_FOOD_TO_FAVORITES',
    'GET_FAVORITE_FOODS',
    'UPDATE_USER_BY_ID',
    'UPDATE_USER_PASSWORD_BY_ID',
    'GET_ALL_CATEGORIES',
    'GET_USER_BY_ID',
    'GET_ORDERS_BY_USER_ID',
  ),
  admin: resolvers(
    'CREATE_ORDER',
    'ATTACH_ORDER',
    'GET_COURIERS',
    'GET_FOOD_BY_ID',
    'CREATE_ORDER',
    'CREATE_CART_ITEM',
    'CREATE_FOOD',
    'GET_DASHBOARD',
    'GET_USERS',
    'GET_ALL_FOODS',
    'CREATE_COURIER',
    'GET_USER_BY_ID',
    'GET_ORDER_BY_ID',
    'UPDATE_FOOD_BY_ID',
    'CREATE_CATEGORY',
    'DELETE_COURIER_BY_ID',
    'GET_ALL_CATEGORIES',
    'GET_CATEGORY_BY_ID',
    'DELIVER_ORDER_BY_ID',
    'RECEIVE_ORDER_BY_ID',
    'START_COOKING_FOOD',
    'UPDATE_CATEGORY_BY_ID',
    'UPDATE_USER_BY_ID',
    'UPDATE_USER_PASSWORD_BY_ID',
    'DELETE_CATEGORY_BY_ID',
    'UPDATE_ORDER_STATUS_BY_ID',
    'GET_CART_ITEMS_BY_USER_ID',
    'GET_ORDERS',
    'ATTACH_ORDER_TO_COURIER',
  ),
  courier: resolvers('DELIVER_ORDER_BY_ID', 'ATTACH_ORDER'),
};
